monitor=,preferred,auto,1
# monitor=eDP-1,disable

exec-once = waybar & hyprpaper & fcitx5

misc {
  disable_hyprland_logo = true;
}

input {
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }
    kb_layout=fr
    kb_options = caps:escape
}

general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    col.active_border = rgb(9a00d5)
    col.inactive_border = rgb(11111b)
    layout = master
}

decoration {
  rounding = 5
}

animations {
    enabled = yes
    bezier = myBezier, 0.16, 1, 0.3, 1

    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, myBezier, popin 80%
    animation = border, 1, 10, myBezier
    animation = fade, 1, 10, myBezier
    animation = workspaces, 1, 10, myBezier
}

master {
    #new_on_top = true
}

gestures {
    workspace_swipe = on
}

windowrule = float, Rofi
windowrule = noborder, Rofi
windowrule = float, title:^(sfml)$
windowrule = center, title:^(sfml)$

$mainMod = SUPER

# keybind for Master layout
bind = $mainMod, o, layoutmsg, orientationnext

bind = $mainMod, A, exec, kitty
bind = $mainMod, F, exec, firefox
bind = $mainMod, T, exec, telegram-desktop
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, E, exec, Thunar
bind = $mainMod, Q, killactive
bind = $mainMod, SPACE, exec, sh $HOME/.config/rofi/bin/launcher
bind = $mainMod, P, exec, sh $HOME/.config/rofi/bin/powermenu
bind = $mainMod, V, togglefloating, 
bind = $mainMod, W, exec, pkill -SIGUSR1 '^waybar$'

# volume control
bind = , xf86audioraisevolume, exec, amixer sset Master 1%+;
bind = , xf86audiolowervolume, exec, amixer sset Master 1%-;

# brightneww control
bind = , xf86monbrightnessup, exec, brightnessctl set 5%+
bind = , xf86monbrightnessdown, exec, brightnessctl set 5%-

# screenshot
bind = , print, exec, grim ~/Pictures/$(date '+%Y-%m-%d-%H:%M:%S').png
bind = $mainMod, S, exec, grim ~/Pictures/$(date '+%Y-%m-%d-%H:%M:%S').png

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9

bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, minus, movetoworkspace, 6
bind = $mainMod SHIFT, egrave, movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla, movetoworkspace, 9

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Move window with mainMod + shift + arrow keys
bindd = $mainMod SHIFT, left, Move window left, movewindow, l
bindd = $mainMod SHIFT, right, Move window right, movewindow, r
bindd = $mainMod SHIFT, up, Move window up, movewindow, u
bindd = $mainMod SHIFT, down, Move window down, movewindow, d

#Resize active windows
bind = $mainMod SHIFT, right, resizeactive, 10 0
bind = $mainMod SHIFT, left, resizeactive, -10 0
bind = $mainMod SHIFT, up, resizeactive, 0 -10
bind = $mainMod SHIFT, down, resizeactive, 0 10
